### ISSUE TITLE
[Feature suggestion] Add possibility to provide a Header title

### ISSUE THREAD

**Issue by nitrofski** [TestRunnerSRL/LiveSplit.Subsplits#4]
When using Section Header and title, it is sometimes odd to have said title being exactly the same as the section split.
I suggest adding a parsing to the section split, where, when both Section Header and the "Show Split Text" option are active, you would be allowed to provide a title which would appear instead of the split text. If the parsing doesn't find anything, the title would be the split, just like the currrent behavior.

Syntax example, using `{...}` (The space before the block would be optional):
- Single: `Gohma {Dragon Roost Cavern}` Would output `Gohma` as the split name, and `Dragon Roost Cavern` as the Header title.
- Double: `Metal Kor {{Done!}}` Would output `Metal Kor {Done!}` as the split name (and section title, inevitably)
- Triple or more:`Spike's Arena {{{Midday Garden}}}` Would output `Spike's Arena` as the split name, and `{Midday Garden}` as the section title.

Obviously, this is not perfect, as it may prevent rare cases of split names to be possible. The syntax is not set in stone.

I think this feature will not be complicated to implement. I wanted to display the idea first, before trying anything.
Thanks for considering it.

Nitrofski

**Comment by TestRunnerSRL** [comment]
In the next major update to subsplits, it'll be possible to have custom names for sections. Section name is displayed in the headers and when the section is collapsed.
